### PR TITLE
Small layouting changes

### PR DESCRIPTION
**Pull request by humdingerb**
* Remove small insets around the list in main window.
* Simplified layout code in data window.
* Use system constants for insets.
* Center align buttons in edit window, add a bit of padding above
  buttons, make window non-resizable.
* Use sentence casing.
* Changed Yes/No alert buttons to Quit/Cancel. Always better to
  have the label be the actual actions.

### CODE REVIEW

**Comment by humdingerb** [comment]
Having the menu bar right on top of the column list may take a bit of time to get used to... :)

You could consider showing the currently open /path/file plus an Open and Save button above the list view instead of the menu bar.

**Comment by humdingerb** [comment]
FYI, I updated the PR to have the edit window be horizontally resizable. I figure that for some data (strings etc.) one may have to deal with longer texts, where wider a window would be handy.

**Comment by andimachovec** [comment]
Thanks for the patches humdinger! Looks much better that way. No space between menu and ColumnListView is a big improvement in particular. And I've learned a lot about the layout api ;-)

**Comment by humdingerb** [comment]
It's always a bit of trial & error for me. Nothing better than experiemting a bit. :)

**Pull request merged**
